/* ══════════════════════════════════════════════════════════════════════════
   WarGrid — seed data (mock backend)
   Everything is generated relative to "now" so countdowns, live matches and
   room-ID release timers always feel alive.
   ══════════════════════════════════════════════════════════════════════════ */
import { MIN, HOUR, DAY } from './utils'

const T0 = Date.now()
export const now = () => Date.now()
const at = (ms) => new Date(T0 + ms).toISOString()

export const MAPS = ['Erangel', 'Miramar', 'Sanhok', 'Vikendi', 'Livik', 'Rondo', 'TDM Warehouse']
export const MODES = ['Solo', 'Duo', 'Squad']

/* ── Organizers ─────────────────────────────────────────────────────────── */
export const ORGANIZERS = {
  wargrid: {
    id: 'wargrid',
    name: 'WarGrid Studios',
    verified: true,
    rating: 4.9,
    events: 142,
    followers: 28400,
    tone: 'blue',
    since: '2022',
    payout: '₹42,18,900 paid out',
    bio: 'Official WarGrid organiser. 140+ BGMI events, zero-payment-dispute record.',
  },
  nova: {
    id: 'nova',
    name: 'Nova Esports India',
    verified: true,
    rating: 4.7,
    events: 96,
    followers: 18200,
    tone: 'violet',
    since: '2021',
    payout: '₹21,04,500 paid out',
    bio: 'Mumbai-based esports org running pro-tier scrims and open cups.',
  },
  clutch: {
    id: 'clutch',
    name: 'Clutch Adda',
    verified: true,
    rating: 4.6,
    events: 61,
    followers: 9800,
    tone: 'green',
    since: '2023',
    payout: '₹7,62,300 paid out',
    bio: 'Community scrim house. Fast lobby creation, tight moderation.',
  },
  aimlab: {
    id: 'aimlab',
    name: 'AimLab India',
    verified: false,
    rating: 4.3,
    events: 22,
    followers: 3100,
    tone: 'yellow',
    since: '2024',
    payout: '₹1,84,000 paid out',
    bio: 'Solo & TDM specialist. Verification in review.',
  },
  zonezero: {
    id: 'zonezero',
    name: 'Zone Zero Orgs',
    verified: true,
    rating: 4.8,
    events: 78,
    followers: 22600,
    tone: 'red',
    since: '2021',
    payout: '₹33,90,700 paid out',
    bio: 'Invitational circuit organiser with anti-cheat monitored lobbies.',
  },
  desi: {
    id: 'desi',
    name: 'Desi Frag Fest',
    verified: true,
    rating: 4.5,
    events: 44,
    followers: 7400,
    tone: 'cyan',
    since: '2023',
    payout: '₹5,11,200 paid out',
    bio: 'Late-night TDM & close-quarter cups.',
  },
}

/* ── Tournaments ────────────────────────────────────────────────────────── */
export const TOURNAMENTS = [
  {
    id: 't0',
    type: 'tournament',
    name: 'WarGrid Weekly Wars #37',
    subtitle: 'Match 3 of 5 · Erangel',
    art: 'art-7',
    mode: 'Squad',
    maps: ['Erangel', 'Miramar', 'Sanhok', 'Livik', 'Rondo'],
    entryFee: 49,
    prizePool: 100000,
    perKill: 150,
    slotsTotal: 100,
    slotsFilled: 100,
    squadSize: 4,
    matches: 5,
    region: 'India · Asia',
    startsAt: at(-26 * MIN),
    endsAt: at(2.2 * HOUR),
    organizer: ORGANIZERS.wargrid,
    status: 'live',
    featured: false,
    tags: ['paid', 'tournament', 'squad', 'live'],
    description:
      'The weekly grind circuit. Five matches across five maps, points-based leaderboard, instant prize payout to WarGrid Wallet.',
    rules: [
      'Room ID & password released 20 minutes before each match on WarGrid.',
      'Emulators strictly banned — device ID verification before Match 1.',
      'Teaming, hacking or exploiting bugs = permanent ban + forfeiture of winnings.',
      'Screenshot of final standings must be submitted by the captain within 10 minutes.',
      'Points: #1 = 15 pts, decreasing by 1 pt per position. Each kill = 1 pt.',
      'Prize credited to wallet within 24 hours of the final match.',
    ],
    prizes: [
      { pos: 1, label: '1st Place', amount: 45000 },
      { pos: 2, label: '2nd Place', amount: 22000 },
      { pos: 3, label: '3rd Place', amount: 12000 },
      { pos: 4, label: '4th – 6th', amount: 5000 },
      { pos: 5, label: 'Top Frag', amount: 6000 },
    ],
    schedule: [
      { n: 'Match 1', time: '7:00 PM', map: 'Erangel', state: 'done' },
      { n: 'Match 2', time: '7:50 PM', map: 'Miramar', state: 'done' },
      { n: 'Match 3', time: '8:40 PM', map: 'Sanhok', state: 'now' },
      { n: 'Match 4', time: '9:30 PM', map: 'Livik', state: 'next' },
      { n: 'Match 5', time: '10:15 PM', map: 'Rondo', state: 'next' },
    ],
    registeredTeams: 100,
    waitlist: 0,
  },
  {
    id: 't1',
    type: 'tournament',
    name: 'WarGrid Conquer Cup — Season 4',
    subtitle: 'India\'s biggest open BGMI circuit',
    art: 'art-1',
    mode: 'Squad',
    maps: ['Erangel', 'Miramar', 'Sanhok', 'Vikendi', 'Livik', 'Rondo'],
    entryFee: 199,
    prizePool: 500000,
    perKill: 250,
    slotsTotal: 128,
    slotsFilled: 112,
    squadSize: 4,
    matches: 6,
    region: 'India · Asia',
    startsAt: at(3 * DAY + 2 * HOUR),
    endsAt: at(4 * DAY + 4 * HOUR),
    organizer: ORGANIZERS.wargrid,
    status: 'open',
    featured: true,
    tags: ['paid', 'tournament', 'squad'],
    description:
      'Season 4 of the Conquer Cup — 128 squads, 6 matches over two days and a ₹5,00,000 prize pool. Top 3 squads get scouted invites to the WarGrid Pro Series.',
    rules: [
      'Squad of 4 with 1 substitute allowed (sub must be registered before Match 1).',
      'All players must be Conqueror/Crown tier or above in the current BGMI season.',
      'Room credentials drop 30 min before every match — check My Matches.',
      'No third-party apps, GFX tools or recoil scripts. Anti-cheat review on top 10 teams.',
      'Entry fee is non-refundable once the lobby is created (24h before Match 1).',
      'Prize split credited within 48 hours of the finals to your WarGrid Wallet.',
    ],
    prizes: [
      { pos: 1, label: 'Champion', amount: 250000 },
      { pos: 2, label: 'Runner-up', amount: 120000 },
      { pos: 3, label: '3rd Place', amount: 60000 },
      { pos: 4, label: '4th – 8th', amount: 8000 },
      { pos: 5, label: 'MVP / Top Frag', amount: 20000 },
      { pos: 6, label: 'Most Survival', amount: 12000 },
    ],
    schedule: [
      { n: 'Day 1 · Match 1', time: '6:00 PM', map: 'Erangel', state: 'next' },
      { n: 'Day 1 · Match 2', time: '7:10 PM', map: 'Miramar', state: 'next' },
      { n: 'Day 1 · Match 3', time: '8:20 PM', map: 'Sanhok', state: 'next' },
      { n: 'Day 2 · Match 4', time: '6:00 PM', map: 'Vikendi', state: 'next' },
      { n: 'Day 2 · Match 5', time: '7:10 PM', map: 'Livik', state: 'next' },
      { n: 'Day 2 · Grand Final', time: '8:30 PM', map: 'Rondo', state: 'next' },
    ],
    registeredTeams: 112,
    waitlist: 23,
  },
  {
    id: 't2',
    type: 'tournament',
    name: 'Bharat Battlegrounds Series #12',
    subtitle: 'Regional qualifiers · North + West',
    art: 'art-2',
    mode: 'Squad',
    maps: ['Erangel', 'Miramar', 'Rondo'],
    entryFee: 99,
    prizePool: 250000,
    perKill: 150,
    slotsTotal: 100,
    slotsFilled: 64,
    squadSize: 4,
    matches: 4,
    region: 'India',
    startsAt: at(5 * DAY + 3 * HOUR),
    endsAt: at(5 * DAY + 8 * HOUR),
    organizer: ORGANIZERS.nova,
    status: 'open',
    featured: true,
    tags: ['paid', 'tournament', 'squad'],
    description:
      'Regional qualifier series with dedicated lobbies for North and West India. Top 12 squads from each region advance to the Bharat Finals.',
    rules: [
      'Region lock: captains must select their server region at registration.',
      '4 matches, best-of points. Tie-breaker on total kills.',
      'Room ID released 25 min before match start.',
      'No smurf accounts — BGMI ID must be 6 months+ old.',
      'Prize pool distributed 50/25/15/10 across top 4.',
    ],
    prizes: [
      { pos: 1, label: '1st Place', amount: 125000 },
      { pos: 2, label: '2nd Place', amount: 62500 },
      { pos: 3, label: '3rd Place', amount: 37500 },
      { pos: 4, label: '4th Place', amount: 25000 },
    ],
    schedule: [
      { n: 'Qualifier A', time: '5:00 PM', map: 'Erangel', state: 'next' },
      { n: 'Qualifier B', time: '6:20 PM', map: 'Miramar', state: 'next' },
      { n: 'Semi Final', time: '7:40 PM', map: 'Erangel', state: 'next' },
      { n: 'Grand Final', time: '9:00 PM', map: 'Rondo', state: 'next' },
    ],
    registeredTeams: 64,
    waitlist: 0,
  },
  {
    id: 't3',
    type: 'tournament',
    name: 'Neon Strike Duo Showdown',
    subtitle: 'Duo-only · fast lobbies · instant payout',
    art: 'art-3',
    mode: 'Duo',
    maps: ['Sanhok', 'Livik'],
    entryFee: 49,
    prizePool: 80000,
    perKill: 200,
    slotsTotal: 64,
    slotsFilled: 61,
    squadSize: 2,
    matches: 3,
    region: 'India',
    startsAt: at(1 * DAY + 1 * HOUR),
    endsAt: at(1 * DAY + 4 * HOUR),
    organizer: ORGANIZERS.clutch,
    status: 'filling',
    featured: true,
    tags: ['paid', 'tournament', 'duo'],
    description:
      'Three fast-paced duo matches on Sanhok and Livik. Only 3 slots left — lobbies fill within hours on Clutch Adda.',
    rules: [
      'Strictly duo — no third player in the lobby.',
      'Both players must join the WarGrid room within 10 minutes of release.',
      'Kill points doubled on Livik match.',
      'Disputes must be raised within 2 hours of match end.',
    ],
    prizes: [
      { pos: 1, label: '1st Duo', amount: 40000 },
      { pos: 2, label: '2nd Duo', amount: 20000 },
      { pos: 3, label: '3rd Duo', amount: 12000 },
      { pos: 4, label: 'Top Fragger', amount: 8000 },
    ],
    schedule: [
      { n: 'Match 1', time: '7:30 PM', map: 'Sanhok', state: 'next' },
      { n: 'Match 2', time: '8:20 PM', map: 'Livik', state: 'next' },
      { n: 'Final', time: '9:10 PM', map: 'Sanhok', state: 'next' },
    ],
    registeredTeams: 61,
    waitlist: 8,
  },
  {
    id: 't4',
    type: 'tournament',
    name: 'Solo Sniper Siege',
    subtitle: 'Free entry · Crossbow + Kar98 only',
    art: 'art-4',
    mode: 'Solo',
    maps: ['Erangel'],
    entryFee: 0,
    prizePool: 40000,
    perKill: 300,
    slotsTotal: 100,
    slotsFilled: 92,
    squadSize: 1,
    matches: 3,
    region: 'India',
    startsAt: at(2 * DAY + 5 * HOUR),
    endsAt: at(2 * DAY + 8 * HOUR),
    organizer: ORGANIZERS.aimlab,
    status: 'filling',
    featured: false,
    tags: ['free', 'tournament', 'solo'],
    description:
      'Snipers only. No ARs, no DMRs — Kar98k, M24, AWM and crossbow. The purest aim test on WarGrid, and it costs you nothing.',
    rules: [
      'Only bolt-action snipers and crossbow allowed.',
      'No vehicles after zone 3.',
      'Screen recording mandatory for top 5 finishers.',
      'Free entry — prize pool funded by WarGrid Studios.',
    ],
    prizes: [
      { pos: 1, label: 'Siege Master', amount: 20000 },
      { pos: 2, label: '2nd Place', amount: 10000 },
      { pos: 3, label: '3rd Place', amount: 6000 },
      { pos: 4, label: 'Longest Kill', amount: 4000 },
    ],
    schedule: [
      { n: 'Heat 1', time: '6:00 PM', map: 'Erangel', state: 'next' },
      { n: 'Heat 2', time: '7:00 PM', map: 'Erangel', state: 'next' },
      { n: 'Siege Final', time: '8:15 PM', map: 'Erangel', state: 'next' },
    ],
    registeredTeams: 92,
    waitlist: 0,
  },
  {
    id: 't5',
    type: 'tournament',
    name: 'Zone Zero Invitational',
    subtitle: 'Invite + premium qualifier · anti-cheat monitored',
    art: 'art-5',
    mode: 'Squad',
    maps: ['Erangel', 'Miramar', 'Sanhok', 'Vikendi', 'Livik', 'Rondo'],
    entryFee: 499,
    prizePool: 1000000,
    perKill: 500,
    slotsTotal: 48,
    slotsFilled: 48,
    squadSize: 4,
    matches: 12,
    region: 'India · Asia',
    startsAt: at(9 * DAY + 2 * HOUR),
    endsAt: at(11 * DAY + 6 * HOUR),
    organizer: ORGANIZERS.zonezero,
    status: 'full',
    featured: true,
    tags: ['paid', 'tournament', 'squad'],
    description:
      'A ₹10,00,000 invitational across 12 matches and 3 days. Every lobby is spectated and reviewed. Waitlist opens automatically when a squad drops out.',
    rules: [
      '48 squads max. Waitlist auto-promotes in order of registration.',
      'Full device verification + face cam for the final day.',
      'Prize money released after KYC of the winning captain.',
      'Substitutions locked 48 hours before Match 1.',
    ],
    prizes: [
      { pos: 1, label: 'Champion', amount: 500000 },
      { pos: 2, label: 'Runner-up', amount: 250000 },
      { pos: 3, label: '3rd Place', amount: 125000 },
      { pos: 4, label: '4th Place', amount: 60000 },
      { pos: 5, label: 'MVP', amount: 40000 },
      { pos: 6, label: 'Top Fragger', amount: 25000 },
    ],
    schedule: [
      { n: 'Day 1 · Group A', time: '4:00 PM', map: 'Erangel', state: 'next' },
      { n: 'Day 1 · Group B', time: '6:30 PM', map: 'Miramar', state: 'next' },
      { n: 'Day 2 · Super Weekend', time: '3:00 PM', map: 'Sanhok', state: 'next' },
      { n: 'Day 3 · Grand Final', time: '5:00 PM', map: 'Rondo', state: 'next' },
    ],
    registeredTeams: 48,
    waitlist: 41,
  },
  {
    id: 't6',
    type: 'tournament',
    name: 'Campus Clash — BGMI Collegiate',
    subtitle: 'College ID required · free entry',
    art: 'art-6',
    mode: 'Squad',
    maps: ['Erangel', 'Sanhok'],
    entryFee: 0,
    prizePool: 120000,
    perKill: 100,
    slotsTotal: 80,
    slotsFilled: 45,
    squadSize: 4,
    matches: 4,
    region: 'India',
    startsAt: at(12 * DAY + 4 * HOUR),
    endsAt: at(12 * DAY + 9 * HOUR),
    organizer: ORGANIZERS.wargrid,
    status: 'open',
    featured: false,
    tags: ['free', 'tournament', 'squad'],
    description:
      'India\'s collegiate BGMI circuit. Register with a valid college email, represent your campus and play for ₹1,20,000 plus internship invites from our partners.',
    rules: [
      'All 4 players must belong to the same institution.',
      'College ID upload required within 24 hours of registration.',
      'Free entry, prize pool funded by WarGrid education partners.',
      'Fair-play pledge signed by the team captain.',
    ],
    prizes: [
      { pos: 1, label: 'Campus Champions', amount: 60000 },
      { pos: 2, label: 'Runner-up', amount: 30000 },
      { pos: 3, label: '3rd Place', amount: 18000 },
      { pos: 4, label: 'Spirit Award', amount: 12000 },
    ],
    schedule: [
      { n: 'Group Stage 1', time: '11:00 AM', map: 'Erangel', state: 'next' },
      { n: 'Group Stage 2', time: '1:00 PM', map: 'Sanhok', state: 'next' },
      { n: 'Semi Final', time: '4:00 PM', map: 'Erangel', state: 'next' },
      { n: 'Grand Final', time: '7:00 PM', map: 'Erangel', state: 'next' },
    ],
    registeredTeams: 45,
    waitlist: 0,
  },
  {
    id: 't7',
    type: 'tournament',
    name: 'Night Raid TDM Cup',
    subtitle: 'TDM · Warehouse & Ruins · starting soon',
    art: 'art-8',
    mode: 'Squad',
    maps: ['TDM Warehouse', 'TDM Ruins'],
    entryFee: 79,
    prizePool: 60000,
    perKill: 50,
    slotsTotal: 32,
    slotsFilled: 30,
    squadSize: 4,
    matches: 6,
    region: 'India',
    startsAt: at(4.5 * HOUR),
    endsAt: at(8 * HOUR),
    organizer: ORGANIZERS.desi,
    status: 'open',
    featured: false,
    tags: ['paid', 'tournament', 'squad'],
    description:
      'Six rounds of pure TDM chaos. First to 40 kills takes the round. Built for squads who want non-stop gunfights instead of a 25-minute rotation.',
    rules: [
      'First squad to 40 kills wins the round.',
      'No shotguns on Warehouse map.',
      'Room ID released 15 min before each round.',
      'Late join = round forfeit, no refund for that round.',
    ],
    prizes: [
      { pos: 1, label: 'Raid Kings', amount: 30000 },
      { pos: 2, label: 'Runner-up', amount: 16000 },
      { pos: 3, label: '3rd Place', amount: 9000 },
      { pos: 4, label: 'Kill Leader', amount: 5000 },
    ],
    schedule: [
      { n: 'Round 1-2', time: '10:00 PM', map: 'Warehouse', state: 'next' },
      { n: 'Round 3-4', time: '10:45 PM', map: 'Ruins', state: 'next' },
      { n: 'Round 5-6', time: '11:30 PM', map: 'Warehouse', state: 'next' },
    ],
    registeredTeams: 30,
    waitlist: 4,
  },
  {
    id: 't8',
    type: 'tournament',
    name: 'Rising Stars Open Qualifier',
    subtitle: 'Free · for unverified & new squads',
    art: 'art-3',
    mode: 'Duo',
    maps: ['Erangel', 'Livik'],
    entryFee: 0,
    prizePool: 25000,
    perKill: 100,
    slotsTotal: 128,
    slotsFilled: 77,
    squadSize: 2,
    matches: 3,
    region: 'India',
    startsAt: at(4 * DAY + 1 * HOUR),
    endsAt: at(4 * DAY + 5 * HOUR),
    organizer: ORGANIZERS.nova,
    status: 'open',
    featured: false,
    tags: ['free', 'tournament', 'duo'],
    description:
      'Your first competitive lobby. No entry fee, no tier requirement, and a scout watching every final circle. Win a slot in Bharat Battlegrounds #13.',
    rules: [
      'Open to all tiers — Ace and below only.',
      'Duo entry, one account per player.',
      'Top 8 duos qualify for Bharat Battlegrounds #13.',
      'Zero tolerance on toxic comms — lobby is spectated.',
    ],
    prizes: [
      { pos: 1, label: '1st Duo', amount: 12000 },
      { pos: 2, label: '2nd Duo', amount: 7000 },
      { pos: 3, label: '3rd Duo', amount: 4000 },
      { pos: 4, label: 'Scout Pick', amount: 2000 },
    ],
    schedule: [
      { n: 'Open Heat 1', time: '5:00 PM', map: 'Erangel', state: 'next' },
      { n: 'Open Heat 2', time: '6:30 PM', map: 'Livik', state: 'next' },
      { n: 'Rising Final', time: '8:00 PM', map: 'Erangel', state: 'next' },
    ],
    registeredTeams: 77,
    waitlist: 0,
  },
]

/* ── Scrims ─────────────────────────────────────────────────────────────── */
export const SCRIMS = [
  {
    id: 's0',
    type: 'scrim',
    name: 'Erangel Prime Scrim #218',
    map: 'Erangel',
    mode: 'Squad',
    entryFee: 0,
    prizePool: 5000,
    perKill: 100,
    slotsTotal: 25,
    slotsFilled: 25,
    squadSize: 4,
    startsAt: at(-14 * MIN),
    organizer: ORGANIZERS.wargrid,
    status: 'live',
    tier: 'Pro',
    tags: ['free', 'scrims', 'squad', 'live'],
    roomId: '88421576',
    roomPass: 'WG@218',
    releaseAt: at(-40 * MIN),
    note: 'Lobby live — Match 1 in progress. Points table updates after the final zone.',
  },
  {
    id: 's1',
    type: 'scrim',
    name: 'Erangel Prime Scrim #219',
    map: 'Erangel',
    mode: 'Squad',
    entryFee: 0,
    prizePool: 5000,
    perKill: 100,
    slotsTotal: 25,
    slotsFilled: 22,
    squadSize: 4,
    startsAt: at(2.5 * HOUR),
    organizer: ORGANIZERS.wargrid,
    status: 'open',
    tier: 'Pro',
    tags: ['free', 'scrims', 'squad', 'today'],
    roomId: null,
    roomPass: null,
    releaseAt: at(2.5 * HOUR - 20 * MIN),
    note: 'Room ID drops 20 minutes before start. Same lobby crew as #218.',
  },
  {
    id: 's2',
    type: 'scrim',
    name: 'Miramar Mayhem — Pro Lobby',
    map: 'Miramar',
    mode: 'Squad',
    entryFee: 25,
    prizePool: 10000,
    perKill: 150,
    slotsTotal: 20,
    slotsFilled: 20,
    squadSize: 4,
    startsAt: at(5 * HOUR),
    organizer: ORGANIZERS.nova,
    status: 'full',
    tier: 'Elite',
    tags: ['paid', 'scrims', 'squad', 'today'],
    roomId: null,
    roomPass: null,
    releaseAt: at(5 * HOUR - 15 * MIN),
    note: 'Lobby full. Join the waitlist — 6 squads usually drop within an hour.',
  },
  {
    id: 's3',
    type: 'scrim',
    name: 'Sanhok Speed Rush',
    map: 'Sanhok',
    mode: 'Squad',
    entryFee: 15,
    prizePool: 6000,
    perKill: 120,
    slotsTotal: 16,
    slotsFilled: 9,
    squadSize: 4,
    startsAt: at(7 * HOUR),
    organizer: ORGANIZERS.clutch,
    status: 'open',
    tier: 'Open',
    tags: ['paid', 'scrims', 'squad', 'today'],
    roomId: null,
    roomPass: null,
    releaseAt: at(7 * HOUR - 25 * MIN),
    note: 'Small lobby, non-stop fights. Hot-drop friendly.',
  },
  {
    id: 's4',
    type: 'scrim',
    name: 'Livik Lightning Blitz',
    map: 'Livik',
    mode: 'Duo',
    entryFee: 0,
    prizePool: 3000,
    perKill: 100,
    slotsTotal: 20,
    slotsFilled: 14,
    squadSize: 2,
    startsAt: at(9 * HOUR),
    organizer: ORGANIZERS.clutch,
    status: 'open',
    tier: 'Open',
    tags: ['free', 'scrims', 'duo', 'today'],
    roomId: null,
    roomPass: null,
    releaseAt: at(9 * HOUR - 20 * MIN),
    note: '15-minute matches. Perfect warm-up before a tournament.',
  },
  {
    id: 's5',
    type: 'scrim',
    name: 'Erangel Night Ops',
    map: 'Erangel',
    mode: 'Squad',
    entryFee: 50,
    prizePool: 20000,
    perKill: 250,
    slotsTotal: 25,
    slotsFilled: 18,
    squadSize: 4,
    startsAt: at(11 * HOUR),
    organizer: ORGANIZERS.zonezero,
    status: 'open',
    tier: 'Elite',
    tags: ['paid', 'scrims', 'squad', 'today'],
    roomId: null,
    roomPass: null,
    releaseAt: at(11 * HOUR - 30 * MIN),
    note: 'Highest paying nightly scrim. Spectated lobby, results auto-verified.',
  },
  {
    id: 's6',
    type: 'scrim',
    name: 'TDM Warehouse Wars',
    map: 'TDM Warehouse',
    mode: 'Squad',
    entryFee: 20,
    prizePool: 8000,
    perKill: 50,
    slotsTotal: 12,
    slotsFilled: 8,
    squadSize: 4,
    startsAt: at(1 * DAY + 1 * HOUR),
    organizer: ORGANIZERS.desi,
    status: 'open',
    tier: 'Open',
    tags: ['paid', 'scrims', 'squad'],
    roomId: null,
    roomPass: null,
    releaseAt: at(1 * DAY + 1 * HOUR - 15 * MIN),
    note: 'First to 40 kills wins. 3 rounds, best of.',
  },
  {
    id: 's7',
    type: 'scrim',
    name: 'Bootcamp Brawl',
    map: 'Erangel',
    mode: 'Squad',
    entryFee: 0,
    prizePool: 2500,
    perKill: 100,
    slotsTotal: 20,
    slotsFilled: 11,
    squadSize: 4,
    startsAt: at(1 * DAY + 3 * HOUR),
    organizer: ORGANIZERS.aimlab,
    status: 'open',
    tier: 'Rookie',
    tags: ['free', 'scrims', 'squad'],
    roomId: null,
    roomPass: null,
    releaseAt: at(1 * DAY + 3 * HOUR - 20 * MIN),
    note: 'Rookie-friendly lobby. Mandatory Bootcamp drop for the first 5 minutes.',
  },
  {
    id: 's8',
    type: 'scrim',
    name: 'Vikendi Frost Cup Scrim',
    map: 'Vikendi',
    mode: 'Squad',
    entryFee: 30,
    prizePool: 12000,
    perKill: 180,
    slotsTotal: 24,
    slotsFilled: 20,
    squadSize: 4,
    startsAt: at(1 * DAY + 6 * HOUR),
    organizer: ORGANIZERS.nova,
    status: 'filling',
    tier: 'Pro',
    tags: ['paid', 'scrims', 'squad'],
    roomId: null,
    roomPass: null,
    releaseAt: at(1 * DAY + 6 * HOUR - 25 * MIN),
    note: 'Snow-map specialists only. Rotation-heavy lobby.',
  },
  {
    id: 's9',
    type: 'scrim',
    name: 'Erangel Prime Scrim #217',
    map: 'Erangel',
    mode: 'Squad',
    entryFee: 0,
    prizePool: 5000,
    perKill: 100,
    slotsTotal: 25,
    slotsFilled: 25,
    squadSize: 4,
    startsAt: at(-1 * DAY - 2 * HOUR),
    organizer: ORGANIZERS.wargrid,
    status: 'completed',
    tier: 'Pro',
    tags: ['free', 'scrims', 'squad', 'completed'],
    roomId: '77310984',
    roomPass: 'WG@217',
    releaseAt: at(-1 * DAY - 2.4 * HOUR),
    note: 'Completed. Points and prize money credited to wallet.',
  },
  {
    id: 's10',
    type: 'scrim',
    name: 'Sanhok Scrim #88',
    map: 'Sanhok',
    mode: 'Squad',
    entryFee: 15,
    prizePool: 6000,
    perKill: 120,
    slotsTotal: 16,
    slotsFilled: 16,
    squadSize: 4,
    startsAt: at(-2 * DAY - 5 * HOUR),
    organizer: ORGANIZERS.clutch,
    status: 'completed',
    tier: 'Open',
    tags: ['paid', 'scrims', 'squad', 'completed'],
    roomId: '55902341',
    roomPass: 'CA#88',
    releaseAt: at(-2 * DAY - 5.5 * HOUR),
    note: 'Completed. Full points table archived.',
  },
]

/* ── Live match state (drives the LIVE card + kill feed) ────────────────── */
export const LIVE_FEED_POOL = [
  { killer: 'GhostRifle', victim: 'xRAZOR', weapon: 'M416 + 6x', zone: 'Pochinki' },
  { killer: 'SN1PER_KING', victim: 'ViperOP', weapon: 'Kar98k', zone: 'School' },
  { killer: 'RaptorX', victim: 'MrFrost', weapon: 'AKM', zone: 'Georgopol' },
  { killer: 'AKSHAY_444', victim: 'NinjaOP', weapon: 'UMP45', zone: 'Mylta' },
  { killer: 'BlitzKrieg', victim: 'SilentKill', weapon: 'DP-28', zone: 'Military Base' },
  { killer: 'GhostRifle', victim: 'ToxicBoy', weapon: 'M24', zone: 'Ruins' },
  { killer: 'HeadHunter', victim: 'RaptorX', weapon: 'Grenade', zone: 'Shelter' },
  { killer: 'ViperOP', victim: 'AKSHAY_444', weapon: 'Mini14', zone: 'Primorsk' },
  { killer: 'SN1PER_KING', victim: 'BlitzKrieg', weapon: 'AWM', zone: 'Quarry' },
  { killer: 'MrFrost', victim: 'HeadHunter', weapon: 'M762', zone: 'Novo' },
]

/* ── User profile ───────────────────────────────────────────────────────── */
export const ME = {
  id: 'u1',
  name: 'Aarav Sharma',
  handle: 'GhostRifle',
  tag: 'WG-7781',
  bgmiId: '51234567890',
  tier: 'Conqueror',
  tierPoints: 5840,
  level: 72,
  xp: 68,
  region: 'Mumbai, IN',
  joined: 'Mar 2024',
  kd: 4.82,
  wins: 128,
  matches: 412,
  earnings: 38450,
  verified: true,
  tone: 'blue',
  role: 'player',
}

/* ── Teams ──────────────────────────────────────────────────────────────── */
export const TEAMS = [
  {
    id: 'team1',
    name: 'Phantom Squad',
    tag: 'PHNT',
    mode: 'Squad',
    art: 'art-1',
    region: 'Mumbai, IN',
    created: 'Jun 2024',
    rank: 148,
    rating: 4.8,
    members: [
      { id: 'p1', name: 'Aarav "GhostRifle"', bgmiId: '51234567890', role: 'IGL', captain: true, kd: 4.82, tier: 'Conqueror', me: true },
      { id: 'p2', name: 'Rohan "RaptorX"', bgmiId: '51882043771', role: 'Assault', captain: false, kd: 3.94, tier: 'Ace' },
      { id: 'p3', name: 'Imran "SN1PER_KING"', bgmiId: '52019884302', role: 'Sniper', captain: false, kd: 5.11, tier: 'Conqueror' },
      { id: 'p4', name: 'Karan "BlitzKrieg"', bgmiId: '51447290183', role: 'Support', captain: false, kd: 3.2, tier: 'Crown' },
    ],
  },
  {
    id: 'team2',
    name: 'Neon Vipers',
    tag: 'NVPR',
    mode: 'Duo',
    art: 'art-3',
    region: 'Delhi, IN',
    created: 'Sep 2024',
    rank: 402,
    rating: 4.5,
    members: [
      { id: 'p1', name: 'Aarav "GhostRifle"', bgmiId: '51234567890', role: 'IGL', captain: true, kd: 4.82, tier: 'Conqueror', me: true },
      { id: 'p5', name: 'Dev "ViperOP"', bgmiId: '53220194877', role: 'Assault', captain: false, kd: 4.05, tier: 'Ace' },
    ],
  },
  {
    id: 'team3',
    name: 'Iron Wolves',
    tag: 'IRWF',
    mode: 'Squad',
    art: 'art-8',
    region: 'Pune, IN',
    created: 'Jan 2025',
    rank: 891,
    rating: 4.2,
    members: [
      { id: 'p6', name: 'Yash "HeadHunter"', bgmiId: '54001298334', role: 'IGL', captain: true, kd: 3.66, tier: 'Crown' },
      { id: 'p7', name: 'Neel "MrFrost"', bgmiId: '54118203944', role: 'Sniper', captain: false, kd: 4.2, tier: 'Ace' },
      { id: 'p8', name: 'Sahil "ToxicBoy"', bgmiId: '54220918477', role: 'Assault', captain: false, kd: 2.98, tier: 'Diamond' },
    ],
  },
]

export const FREE_AGENTS = [
  { id: 'f1', name: 'Aditya "AKSHAY_444"', bgmiId: '55102938471', role: 'Assault', kd: 3.4, tier: 'Ace' },
  { id: 'f2', name: 'Rehan "SilentKill"', bgmiId: '55220193844', role: 'Sniper', kd: 4.6, tier: 'Conqueror' },
  { id: 'f3', name: 'Manav "xRAZOR"', bgmiId: '55330918277', role: 'Support', kd: 2.8, tier: 'Crown' },
  { id: 'f4', name: 'Farhan "NinjaOP"', bgmiId: '55441209388', role: 'Assault', kd: 3.15, tier: 'Diamond' },
  { id: 'f5', name: 'Vikram "ZoneGod"', bgmiId: '55550291837', role: 'IGL', kd: 3.9, tier: 'Ace' },
]

/* ── Bookings (My Matches) ──────────────────────────────────────────────── */
export const BOOKINGS = [
  {
    id: 'bk_1001',
    eventId: 's1',
    eventType: 'scrim',
    teamId: 'team1',
    status: 'confirmed',
    amount: 0,
    bookedAt: at(-3 * HOUR),
    players: [
      { name: 'Aarav "GhostRifle"', bgmiId: '51234567890', role: 'IGL' },
      { name: 'Rohan "RaptorX"', bgmiId: '51882043771', role: 'Assault' },
      { name: 'Imran "SN1PER_KING"', bgmiId: '52019884302', role: 'Sniper' },
      { name: 'Karan "BlitzKrieg"', bgmiId: '51447290183', role: 'Support' },
    ],
    roomId: null,
    roomPass: null,
    result: null,
  },
  {
    id: 'bk_1002',
    eventId: 't1',
    eventType: 'tournament',
    teamId: 'team1',
    status: 'confirmed',
    amount: 199,
    bookedAt: at(-2 * DAY),
    players: [
      { name: 'Aarav "GhostRifle"', bgmiId: '51234567890', role: 'IGL' },
      { name: 'Rohan "RaptorX"', bgmiId: '51882043771', role: 'Assault' },
      { name: 'Imran "SN1PER_KING"', bgmiId: '52019884302', role: 'Sniper' },
      { name: 'Karan "BlitzKrieg"', bgmiId: '51447290183', role: 'Support' },
    ],
    roomId: null,
    roomPass: null,
    result: null,
    seatNo: 17,
  },
  {
    id: 'bk_1003',
    eventId: 't3',
    eventType: 'tournament',
    teamId: 'team2',
    status: 'confirmed',
    amount: 49,
    bookedAt: at(-6 * HOUR),
    players: [
      { name: 'Aarav "GhostRifle"', bgmiId: '51234567890', role: 'IGL' },
      { name: 'Dev "ViperOP"', bgmiId: '53220194877', role: 'Assault' },
    ],
    roomId: null,
    roomPass: null,
    result: null,
    seatNo: 4,
  },
  {
    id: 'bk_1004',
    eventId: 's9',
    eventType: 'scrim',
    teamId: 'team1',
    status: 'completed',
    amount: 0,
    bookedAt: at(-1 * DAY - 8 * HOUR),
    players: [
      { name: 'Aarav "GhostRifle"', bgmiId: '51234567890', role: 'IGL' },
      { name: 'Rohan "RaptorX"', bgmiId: '51882043771', role: 'Assault' },
      { name: 'Imran "SN1PER_KING"', bgmiId: '52019884302', role: 'Sniper' },
      { name: 'Karan "BlitzKrieg"', bgmiId: '51447290183', role: 'Support' },
    ],
    roomId: '77310984',
    roomPass: 'WG@217',
    result: { position: 3, kills: 14, points: 51, earned: 1500, wwcd: false, damage: 2410 },
  },
  {
    id: 'bk_1005',
    eventId: 't5',
    eventType: 'tournament',
    teamId: 'team1',
    status: 'waitlist',
    amount: 0,
    bookedAt: at(-12 * HOUR),
    players: [
      { name: 'Aarav "GhostRifle"', bgmiId: '51234567890', role: 'IGL' },
      { name: 'Rohan "RaptorX"', bgmiId: '51882043771', role: 'Assault' },
      { name: 'Imran "SN1PER_KING"', bgmiId: '52019884302', role: 'Sniper' },
      { name: 'Karan "BlitzKrieg"', bgmiId: '51447290183', role: 'Support' },
    ],
    waitlistPos: 3,
    roomId: null,
    roomPass: null,
    result: null,
  },
  {
    id: 'bk_1006',
    eventId: 's10',
    eventType: 'scrim',
    teamId: 'team3',
    status: 'completed',
    amount: 15,
    bookedAt: at(-3 * DAY),
    players: [
      { name: 'Yash "HeadHunter"', bgmiId: '54001298334', role: 'IGL' },
      { name: 'Neel "MrFrost"', bgmiId: '54118203944', role: 'Sniper' },
      { name: 'Sahil "ToxicBoy"', bgmiId: '54220918477', role: 'Assault' },
      { name: 'Aarav "GhostRifle"', bgmiId: '51234567890', role: 'Support' },
    ],
    roomId: '55902341',
    roomPass: 'CA#88',
    result: { position: 1, kills: 19, points: 66, earned: 4200, wwcd: true, damage: 3120 },
  },
]

/* ── Wallet ─────────────────────────────────────────────────────────────── */
export const WALLET = {
  balance: 4850,
  winnings: 12400,
  blocked: 0,
  kyc: 'Verified',
  upi: 'aarav@okhdfc',
  transactions: [
    { id: 'tx1', kind: 'credit', type: 'Prize money', label: 'Sanhok Scrim #88 · 1st place', amount: 4200, at: at(-2 * DAY - 3 * HOUR), method: 'Wallet' },
    { id: 'tx2', kind: 'debit', type: 'Entry fee', label: 'Sanhok Scrim #88', amount: 15, at: at(-3 * DAY), method: 'Wallet' },
    { id: 'tx3', kind: 'credit', type: 'Added money', label: 'UPI · aarav@okhdfc', amount: 1000, at: at(-3 * DAY - 4 * HOUR), method: 'UPI' },
    { id: 'tx4', kind: 'debit', type: 'Entry fee', label: 'Conquer Cup S4 · Phantom Squad', amount: 199, at: at(-2 * DAY), method: 'Wallet' },
    { id: 'tx5', kind: 'credit', type: 'Prize money', label: 'Erangel Prime Scrim #217 · 3rd place', amount: 1500, at: at(-1 * DAY - 1 * HOUR), method: 'Wallet' },
    { id: 'tx6', kind: 'debit', type: 'Entry fee', label: 'Neon Strike Duo Showdown', amount: 49, at: at(-6 * HOUR), method: 'Wallet' },
    { id: 'tx7', kind: 'debit', type: 'Withdrawal', label: 'To HDFC ••••4471', amount: 5000, at: at(-5 * DAY), method: 'Bank' },
    { id: 'tx8', kind: 'credit', type: 'Refund', label: 'Miramar Mayhem · lobby cancelled', amount: 25, at: at(-7 * DAY), method: 'Wallet' },
    { id: 'tx9', kind: 'credit', type: 'Cashback', label: 'WarGrid Fest · 10% back', amount: 20, at: at(-8 * DAY), method: 'Wallet' },
  ],
}

/* ── Notifications ──────────────────────────────────────────────────────── */
export const NOTIFICATIONS = [
  {
    id: 'n1',
    kind: 'room',
    tone: 'gold',
    title: 'Room ID released — Erangel Prime Scrim #218',
    body: 'Room 88421576 · Pass WG@218. Join within 10 minutes.',
    at: at(-18 * MIN),
    read: false,
    eventId: 's0',
  },
  {
    id: 'n2',
    kind: 'match',
    tone: 'red',
    title: 'Match starting soon',
    body: 'Neon Strike Duo Showdown begins in 1 day. Warm-up lobby opens 30 min prior.',
    at: at(-42 * MIN),
    read: false,
    eventId: 't3',
  },
  {
    id: 'n3',
    kind: 'prize',
    tone: 'green',
    title: '₹1,500 prize credited',
    body: '3rd place · Erangel Prime Scrim #217 has been paid to your WarGrid Wallet.',
    at: at(-1 * DAY - 1 * HOUR),
    read: false,
    eventId: 's9',
  },
  {
    id: 'n4',
    kind: 'booking',
    tone: 'blue',
    title: 'Registration confirmed',
    body: 'Phantom Squad is locked into WarGrid Conquer Cup — Season 4 (Seat #17).',
    at: at(-2 * DAY),
    read: true,
    eventId: 't1',
  },
  {
    id: 'n5',
    kind: 'result',
    tone: 'blue',
    title: 'Results published',
    body: 'Sanhok Scrim #88 points table is live. You finished #1 with 19 kills.',
    at: at(-2 * DAY - 4 * HOUR),
    read: true,
    eventId: 's10',
  },
  {
    id: 'n6',
    kind: 'new',
    tone: 'gold',
    title: 'New tournament near you',
    body: 'Zone Zero Invitational · ₹10,00,000 prize pool just opened waitlisting.',
    at: at(-3 * DAY),
    read: true,
    eventId: 't5',
  },
  {
    id: 'n7',
    kind: 'booking',
    tone: 'blue',
    title: 'Waitlist update',
    body: 'You moved to position #3 on the Zone Zero Invitational waitlist.',
    at: at(-12 * HOUR),
    read: false,
    eventId: 't5',
  },
  {
    id: 'n8',
    kind: 'team',
    tone: 'blue',
    title: 'Teammate invite accepted',
    body: 'Karan "BlitzKrieg" joined Phantom Squad as Support.',
    at: at(-4 * DAY),
    read: true,
  },
  {
    id: 'n9',
    kind: 'system',
    tone: 'green',
    title: 'KYC verified',
    body: 'Your wallet is withdrawal-ready. Limits raised to ₹50,000/day.',
    at: at(-6 * DAY),
    read: true,
  },
]

/* ── Leaderboards ───────────────────────────────────────────────────────── */
export const LB_PLAYERS = [
  { id: 'l1', name: 'Imran "SN1PER_KING"', team: 'Phantom Squad', kills: 1842, points: 24180, wins: 96, earnings: 184500, matches: 402, kd: 5.11, me: false },
  { id: 'l2', name: 'Rehan "SilentKill"', team: 'Nova Prime', kills: 1790, points: 23420, wins: 88, earnings: 162000, matches: 411, kd: 4.96, me: false },
  { id: 'l3', name: 'Vikram "ZoneGod"', team: 'Zone Zero Elite', kills: 1688, points: 22910, wins: 92, earnings: 158400, matches: 388, kd: 4.71, me: false },
  { id: 'l4', name: 'Aarav "GhostRifle"', team: 'Phantom Squad', kills: 1655, points: 22480, wins: 128, earnings: 138450, matches: 412, kd: 4.82, me: true },
  { id: 'l5', name: 'Neel "MrFrost"', team: 'Iron Wolves', kills: 1602, points: 21140, wins: 71, earnings: 96200, matches: 396, kd: 4.2, me: false },
  { id: 'l6', name: 'Aditya "AKSHAY_444"', team: 'Desi Fraggers', kills: 1544, points: 20380, wins: 66, earnings: 88400, matches: 401, kd: 3.94, me: false },
  { id: 'l7', name: 'Dev "ViperOP"', team: 'Neon Vipers', kills: 1501, points: 19870, wins: 63, earnings: 81250, matches: 372, kd: 4.05, me: false },
  { id: 'l8', name: 'Rohan "RaptorX"', team: 'Phantom Squad', kills: 1466, points: 19240, wins: 59, earnings: 74800, matches: 389, kd: 3.94, me: false },
  { id: 'l9', name: 'Manav "xRAZOR"', team: 'Clutch Kings', kills: 1398, points: 18120, wins: 52, earnings: 62100, matches: 366, kd: 3.62, me: false },
  { id: 'l10', name: 'Farhan "NinjaOP"', team: 'Nova Prime', kills: 1341, points: 17480, wins: 48, earnings: 58900, matches: 358, kd: 3.5, me: false },
  { id: 'l11', name: 'Yash "HeadHunter"', team: 'Iron Wolves', kills: 1288, points: 16640, wins: 44, earnings: 47200, matches: 351, kd: 3.66, me: false },
  { id: 'l12', name: 'Sahil "ToxicBoy"', team: 'Iron Wolves', kills: 1180, points: 15220, wins: 37, earnings: 31600, matches: 340, kd: 2.98, me: false },
]

export const LB_TEAMS = [
  { id: 'm1', name: 'Zone Zero Elite', tag: 'ZZE', wins: 214, points: 88420, kills: 6120, earnings: 1284000, matches: 610, mine: false },
  { id: 'm2', name: 'Nova Prime', tag: 'NVPM', wins: 198, points: 84110, kills: 5880, earnings: 1042500, matches: 598, mine: false },
  { id: 'm3', name: 'Phantom Squad', tag: 'PHNT', wins: 186, points: 81640, kills: 5742, earnings: 884300, matches: 588, mine: true },
  { id: 'm4', name: 'Clutch Kings', tag: 'CLKG', wins: 161, points: 74220, kills: 5180, earnings: 702400, matches: 561, mine: false },
  { id: 'm5', name: 'Desi Fraggers', tag: 'DSFR', wins: 149, points: 70180, kills: 4990, earnings: 618200, matches: 544, mine: false },
  { id: 'm6', name: 'Iron Wolves', tag: 'IRWF', wins: 132, points: 64880, kills: 4620, earnings: 488100, matches: 522, mine: false },
  { id: 'm7', name: 'Neon Vipers', tag: 'NVPR', wins: 118, points: 58240, kills: 4180, earnings: 392600, matches: 498, mine: true },
  { id: 'm8', name: 'Bootcamp Boys', tag: 'BTCP', wins: 104, points: 51880, kills: 3820, earnings: 314000, matches: 476, mine: false },
]

/* ── Organizer dashboard ────────────────────────────────────────────────── */
export const ORGANIZER_ME = ORGANIZERS.wargrid

export const ORG_EVENTS = [
  {
    id: 't1',
    name: 'Conquer Cup — Season 4',
    type: 'Tournament',
    status: 'Registrations open',
    slots: '112 / 128',
    revenue: 22288,
    startsAt: at(3 * DAY + 2 * HOUR),
    art: 'art-1',
  },
  {
    id: 't0',
    name: 'Weekly Wars #37',
    type: 'Tournament',
    status: 'LIVE now',
    slots: '100 / 100',
    revenue: 4900,
    startsAt: at(-26 * MIN),
    art: 'art-7',
  },
  {
    id: 's0',
    name: 'Erangel Prime Scrim #218',
    type: 'Scrim',
    status: 'LIVE now',
    slots: '25 / 25',
    revenue: 0,
    startsAt: at(-14 * MIN),
    art: 'art-3',
  },
  {
    id: 's1',
    name: 'Erangel Prime Scrim #219',
    type: 'Scrim',
    status: 'Room ID locked',
    slots: '22 / 25',
    revenue: 0,
    startsAt: at(2.5 * HOUR),
    art: 'art-3',
  },
  {
    id: 't6',
    name: 'Campus Clash Collegiate',
    type: 'Tournament',
    status: 'Pending admin approval',
    slots: '45 / 80',
    revenue: 0,
    startsAt: at(12 * DAY + 4 * HOUR),
    art: 'art-6',
  },
]

export const ORG_PARTICIPANTS = [
  { id: 'r1', team: 'Phantom Squad', tag: 'PHNT', captain: 'GhostRifle', players: 4, paid: true, seat: 17, status: 'Verified', checked: true },
  { id: 'r2', team: 'Zone Zero Elite', tag: 'ZZE', captain: 'ZoneGod', players: 4, paid: true, seat: 3, status: 'Verified', checked: true },
  { id: 'r3', team: 'Nova Prime', tag: 'NVPM', captain: 'SilentKill', players: 4, paid: true, seat: 8, status: 'Verified', checked: true },
  { id: 'r4', team: 'Clutch Kings', tag: 'CLKG', captain: 'xRAZOR', players: 4, paid: false, seat: 22, status: 'Payment pending', checked: false },
  { id: 'r5', team: 'Desi Fraggers', tag: 'DSFR', captain: 'AKSHAY_444', players: 4, paid: true, seat: 31, status: 'Verified', checked: true },
  { id: 'r6', team: 'Iron Wolves', tag: 'IRWF', captain: 'HeadHunter', players: 3, paid: true, seat: 44, status: 'Roster incomplete', checked: false },
  { id: 'r7', team: 'Bootcamp Boys', tag: 'BTCP', captain: 'NinjaOP', players: 4, paid: true, seat: 51, status: 'Verified', checked: true },
  { id: 'r8', team: 'Neon Vipers', tag: 'NVPR', captain: 'ViperOP', players: 2, paid: false, seat: 60, status: 'Flagged — wrong mode', checked: false },
]

export const ORG_EARNINGS = {
  total: 1284900,
  month: 184320,
  pending: 42180,
  fee: 5,
  spark: [38, 52, 44, 68, 59, 74, 66, 88, 79, 96, 84, 100],
  rows: [
    { id: 'e1', event: 'Conquer Cup S4', gross: 22288, fee: 1114, net: 21174, status: 'In escrow', at: at(-2 * DAY) },
    { id: 'e2', event: 'Weekly Wars #37', gross: 4900, fee: 245, net: 4655, status: 'Settling', at: at(-3 * HOUR) },
    { id: 'e3', event: 'Erangel Prime #217', gross: 0, fee: 0, net: 0, status: 'Free scrim', at: at(-1 * DAY) },
    { id: 'e4', event: 'Weekly Wars #36', gross: 4760, fee: 238, net: 4522, status: 'Paid', at: at(-8 * DAY) },
    { id: 'e5', event: 'Campus Clash (prev)', gross: 0, fee: 0, net: 0, status: 'Paid', at: at(-16 * DAY) },
  ],
}

export const ORG_RESULTS_TEMPLATE = [
  { pos: 1, team: 'Zone Zero Elite', tag: 'ZZE', kills: 21, points: 68 },
  { pos: 2, team: 'Nova Prime', tag: 'NVPM', kills: 18, points: 62 },
  { pos: 3, team: 'Phantom Squad', tag: 'PHNT', kills: 14, points: 51 },
  { pos: 4, team: 'Clutch Kings', tag: 'CLKG', kills: 12, points: 44 },
  { pos: 5, team: 'Desi Fraggers', tag: 'DSFR', kills: 9, points: 38 },
  { pos: 6, team: 'Iron Wolves', tag: 'IRWF', kills: 7, points: 31 },
]

/* ── Admin panel ────────────────────────────────────────────────────────── */
export const ADMIN_STATS = {
  users: 184320,
  newToday: 412,
  organizers: 1284,
  liveEvents: 17,
  gmv: 4218400,
  gmvToday: 184300,
  disputes: 6,
  flagged: 11,
  spark: [42, 55, 48, 62, 71, 66, 80, 74, 92, 88, 100, 96],
}

export const ADMIN_USERS = [
  { id: 'a1', name: 'Aarav Sharma', handle: 'GhostRifle', role: 'Player', joined: 'Mar 2024', events: 68, spend: 8420, status: 'Active', tone: 'blue' },
  { id: 'a2', name: 'Imran Khan', handle: 'SN1PER_KING', role: 'Player', joined: 'Jan 2024', events: 94, spend: 12840, status: 'Active', tone: 'green' },
  { id: 'a3', name: 'Rhea Menon', handle: 'QueenFrag', role: 'Organizer', joined: 'Aug 2023', events: 61, spend: 0, status: 'Active', tone: 'violet' },
  { id: 'a4', name: 'Sahil Verma', handle: 'ToxicBoy', role: 'Player', joined: 'Jun 2025', events: 12, spend: 340, status: 'Flagged', tone: 'yellow' },
  { id: 'a5', name: 'Anonymous', handle: 'HackerX99', role: 'Player', joined: 'Sep 2025', events: 2, spend: 0, status: 'Banned', tone: 'red' },
  { id: 'a6', name: 'Dev Patel', handle: 'ViperOP', role: 'Player', joined: 'Feb 2024', events: 77, spend: 6120, status: 'Active', tone: 'cyan' },
  { id: 'a7', name: 'Nikhil Rao', handle: 'SmurfLord', role: 'Player', joined: 'Sep 2025', events: 4, spend: 90, status: 'Flagged', tone: 'yellow' },
]

export const ADMIN_VERIFICATIONS = [
  { id: 'v1', org: 'AimLab India', owner: 'Rhea Menon', docs: 'GST + PAN + Aadhaar', submitted: at(-2 * DAY), followers: 3100, events: 22, risk: 'Low' },
  { id: 'v2', org: 'Bombay Battlehouse', owner: 'Farhan Q.', docs: 'PAN + Aadhaar', submitted: at(-5 * HOUR), followers: 840, events: 3, risk: 'Medium' },
  { id: 'v3', org: 'Punjab Frag League', owner: 'Gurpreet S.', docs: 'GST + PAN', submitted: at(-11 * HOUR), followers: 5200, events: 14, risk: 'Low' },
  { id: 'v4', org: 'ShadowOps Esports', owner: 'Unknown', docs: 'Aadhaar only', submitted: at(-40 * MIN), followers: 60, events: 0, risk: 'High' },
]

export const ADMIN_APPROVALS = [
  { id: 'ap1', event: 'Campus Clash — Collegiate', org: 'WarGrid Studios', prize: 120000, entry: 0, slots: 80, submitted: at(-4 * HOUR), type: 'Tournament', risk: 'Low' },
  { id: 'ap2', event: 'Midnight Massacre #9', org: 'Desi Frag Fest', prize: 45000, entry: 59, slots: 40, submitted: at(-9 * HOUR), type: 'Tournament', risk: 'Low' },
  { id: 'ap3', event: '₹1 Crore Solo Rumble', org: 'ShadowOps Esports', prize: 10000000, entry: 9, slots: 1000, submitted: at(-2 * HOUR), type: 'Tournament', risk: 'High' },
  { id: 'ap4', event: 'Erangel Warmup #219', org: 'WarGrid Studios', prize: 5000, entry: 0, slots: 25, submitted: at(-1 * HOUR), type: 'Scrim', risk: 'Low' },
]

export const ADMIN_PAYMENTS = [
  { id: 'p1', txn: 'WG-991284', user: 'GhostRifle', event: 'Conquer Cup S4', amount: 199, method: 'Wallet', status: 'Success', at: at(-2 * DAY) },
  { id: 'p2', txn: 'WG-991290', user: 'ViperOP', event: 'Neon Strike Duo', amount: 49, method: 'UPI', status: 'Success', at: at(-6 * HOUR) },
  { id: 'p3', txn: 'WG-991301', user: 'xRAZOR', event: 'Conquer Cup S4', amount: 199, method: 'Card', status: 'Pending', at: at(-22 * MIN) },
  { id: 'p4', txn: 'WG-991308', user: 'HeadHunter', event: 'Erangel Night Ops', amount: 50, method: 'UPI', status: 'Failed', at: at(-14 * MIN) },
  { id: 'p5', txn: 'WG-991312', user: 'SilentKill', event: 'Zone Zero Invitational', amount: 499, method: 'Wallet', status: 'Success', at: at(-8 * MIN) },
  { id: 'p6', txn: 'WG-991255', user: 'AKSHAY_444', event: 'Withdrawal → HDFC', amount: 12000, method: 'Bank', status: 'Processing', at: at(-3 * HOUR) },
]

export const ADMIN_DISPUTES = [
  { id: 'd1', ref: 'DSP-2214', user: 'ToxicBoy', event: 'Sanhok Scrim #88', type: 'Prize not credited', amount: 1200, age: '4h', priority: 'High', status: 'Open' },
  { id: 'd2', ref: 'DSP-2213', user: 'NinjaOP', event: 'Miramar Mayhem', type: 'Lobby cancelled / refund', amount: 25, age: '9h', priority: 'Low', status: 'Open' },
  { id: 'd3', ref: 'DSP-2210', user: 'MrFrost', event: 'Weekly Wars #36', type: 'Opponent teaming allegation', amount: 0, age: '1d', priority: 'Medium', status: 'In review' },
  { id: 'd4', ref: 'DSP-2208', user: 'ZoneGod', event: 'Night Raid TDM Cup', type: 'Wrong result recorded', amount: 9000, age: '2d', priority: 'High', status: 'Resolved' },
]

export const ADMIN_REPORTS = [
  { id: 'rp1', target: 'HackerX99', reason: 'Aimbot in Erangel Prime Scrim #216', by: '12 players', severity: 'Critical', at: at(-3 * HOUR), status: 'Open' },
  { id: 'rp2', target: 'SmurfLord', reason: 'Smurf account / tier fraud', by: '4 players', severity: 'High', at: at(-7 * HOUR), status: 'Open' },
  { id: 'rp3', target: 'ToxicBoy', reason: 'Abusive voice comms', by: '2 players', severity: 'Medium', at: at(-1 * DAY), status: 'In review' },
  { id: 'rp4', target: 'ShadowOps Esports', reason: 'Unrealistic prize pool claim', by: 'Admin AI', severity: 'High', at: at(-2 * HOUR), status: 'Open' },
]

export const ADMIN_BANNED = [
  { id: 'b1', handle: 'HackerX99', reason: 'Aimbot (verified)', since: at(-2 * HOUR), duration: 'Permanent', device: '3 linked devices' },
  { id: 'b2', handle: 'FakePrize_Org', reason: 'Prize fraud — 4 disputes', since: at(-6 * DAY), duration: 'Permanent', device: '1 device' },
  { id: 'b3', handle: 'TeamSeller21', reason: 'Slot selling / account sharing', since: at(-11 * DAY), duration: '90 days', device: '2 devices' },
]

/* ── Filter definitions ─────────────────────────────────────────────────── */
export const HOME_FILTERS = [
  { id: 'all', label: 'All Battles' },
  { id: 'live', label: 'Live Now' },
  { id: 'free', label: 'Free' },
  { id: 'paid', label: 'Paid' },
  { id: 'scrims', label: 'Scrims' },
  { id: 'tournament', label: 'Tournament' },
  { id: 'solo', label: 'Solo' },
  { id: 'duo', label: 'Duo' },
  { id: 'squad', label: 'Squad' },
]

export const SCRAMBLE_WORDS = [
  'PLAY.',
  'COMPETE.',
  'CONQUER.',
]
